POST http://localhost:3000/register
content-type: application/json

{
    "email": "vishwaspaikra008@gmail.com",
    "password": "hello"
}

###

POST http://localhost:3000/login
content-type: application/json

{
    "email": "vishwaspaikra007@gmail.com",
    "password": "hello"
}

###

GET http://localhost:3000/check
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1ZWNkMDE1YTRmZTg0ZDIzMjQ1OTIwNTUiLCJhZ2UiOjI0LCJwb3N0Ijo0MCwiaWF0IjoxNTkxMzUwODQxLCJleHAiOjE1OTEzNTE3NDF9.KKGrjhtidZryav_JKXH6heN4as_IUKtTYhqcrK2kOew

###
POST http://localhost:3000/showToken
content-type: application/json

{
   "email": "vishwaspaikra007@gmail.com",
    "password": "hello" 
}
