POST http://localhost:3000/register
content-type: application/json

{
    "email": "vishwaspaikra00@gmail.com",
    "password": "hello"
}

###

POST http://localhost:3000/login
content-type: application/json

{
    "email": "vishwaspaikra007@gmail.com",
    "PWD": "vishwas"
}

###

GET http://localhost:3000/check
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1ZWVhNWQ5YWM1ZjM3MzNjZGYwZmVhMDkiLCJhZ2UiOjI0LCJwb3N0Ijo0MCwiaWF0IjoxNTkyNDg3MTk3LCJleHAiOjE1OTI0ODgwOTd9.dwPYjQtwk3fNpVyOELbUPnMk-ziOlIRE7kRoFBri0ig

###
POST http://localhost:3000/showToken
content-type: application/json

{
   "email": "vishwaspaikra007@gmail.com",
    "password": "hello" 
}

###
POST http://localhost:3000/requestMail
content-type: application/json

{
   "to": "vishwaspaikra007@gmail.com"
}

###
POST http://localhost:3000/verifyOTP
content-type: application/json

{
   "email": "vishwaspaikra007@gmail.com",
   "otp": 797596
}